# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

env:
  - DB=MYSQL CORE_RELEASE=3.6

matrix:
  include:
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.5
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit cwp-core/tests
